### ISSUE TITLE
gitomator-make-access-permissions complains about admin

### ISSUE THREAD

**Issue by jmzaleski** [gitomator/gitomator#10]
gitomator-make-access-permissions a3-repo.yaml

```
default_access_permission: write

repo_properties:
  description: "initally empty repo, intended for csc302 a3"
  private: true

repos:
 - test2-repo-freundj: {joeyfreund-test2: write, Gadal: admin, garysong23: admin}
 - test2-repo-zaleskim: {test-jmzaleski: write, Gadal: admin, garysong23: admin}
```

fails with

I, [2017-02-03T18:18:45.094873 #27]  INFO -- : Granting user joeyfreund-test2 write permission to test2-repo-freundj
I, [2017-02-03T18:18:45.406185 #27]  INFO -- : Granting user Gadal admin permission to test2-repo-freundj
ERROR: Invalid permission 'admin'.

/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:231:in `_strinigify_permission'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/github/hosting_provider.rb:192:in `set_user_permission'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service.rb:49:in `service_call'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/service/hosting.rb:133:in `set_user_permission'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/update_repo_access_permissions.rb:29:in `block in run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/update_repo_access_permissions.rb:27:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/task/update_repo_access_permissions.rb:27:in `run'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:61:in `block in run_tasks'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:61:in `each'
	/usr/local/bundle/gems/gitomator-0.1.2.3/lib/gitomator/util/script_util.rb:61:in `run_tasks'
	/usr/local/bundle/gems/gitomator-0.1.2.3/bin/gitomator-make-access-permissions:72:in `<top (required)>'
	/usr/local/bundle/bin/gitomator-make-access-permissions:22:in `load'
	/usr/local/bundle/bin/gitomator-make-access-permissions:22:in `<main>'
