### ISSUE TITLE
gitomator-make-repos didn make them private??

### ISSUE THREAD

**Issue by jmzaleski** [gitomator/gitomator#13]
I wouldn't take this issue too seriously, I'm a bit confused about the context.

Did I goof this yaml, or did the tool bug out, or do I remember incorrectly??
It could be that I had made the team from an earlier run, and forgot the private flag, and it wasn't applied on a subsequent run. or may other things. it was a extended gitomator session.

default_access_permission: write

repo_properties:
  description: "initally empty repo, intended for csc302 project"
  private: true

repos:
  - proj-ShipItPartyParrots: 
    -    dengjeffrey : write
    -       g2hchang : write
    -         hiei23 : write
    -   josephfu1994 : write
    -         dashed : write
    -        moni-li : write
    -     garysong23 : write

**Comment by joeyfreund** [comment]
Strange, is the YAML file indented correctly? That is:

```yaml
repo_properties:
    description: "Initially empty repo, intended for csc302 project"
    private: true
```

 > _Note:_ `description` and `private` are indented (i.e. nested) under `repo_properties`.
