### ISSUE TITLE
Select between ssh/http in make-repos

### ISSUE THREAD

**Issue by joeyfreund** [gitomator/gitomator#8]
It is not clear whether `clone_url` returns the SSH or HTTP url in [this line of code](https://github.com/gitomator/gitomator/blob/master/lib/gitomator/task/make_repos.rb#L68).

Need to:
 1. Find the RubyDocs for `clone_url` 
 2. Figure out an elegant way for configuring which URL to use

**Comment by joeyfreund** [comment]
With the commit above, we can now specify the protocol in the `.gitomator` as follows:

```yaml
hosting:
  provider: github
  access_token: YOUR-GITHUB-ACCESS-TOKEN
  organization: YOUR-GITHUB-ORGANIZATION
  default_protocol: ssh  # Optional config, can be either https or ssh

ci:
  provider: travis_pro
  access_token: YOUR-TRAVIS-CI-ACCESS-TOKEN
  github_organization: YOUR-GITHUB-ORGANIZATION
```
